# Copyright (c) 2026 The Frontier Framework Authors
# SPDX-License-Identifier: Apache-2.0 OR MIT

[app]
name = "Polyglot Calc"
version = "1.0.0"
description = "High-performance polyglot calculator"
copyright = "Â© 2026 Frontier Org"
author = "Frontier Dev"
icon = "app/frontend/icon.ico"